<a href="https://colab.research.google.com/github/riccardogs/PyTorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.



Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation.

In [1]:
import torch
# import torch: importa la libreria principale di PyTorch
# - torch: è il pacchetto fondamentale di PyTorch che contiene:
#   * Tensor: la struttura dati principale (simile a numpy array ma con supporto GPU)
#   * Funzioni matematiche e operazioni sui tensor
#   * Supporto per autograd (differenziazione automatica)
#   * Moduli per reti neurali (torch.nn)
#   * Ottimizzatori (torch.optim)
#   * Utilità per dataset (torch.utils.data)
# - Dopo questo import, possiamo usare torch.tensor(), torch.zeros(), torch.ones(), ecc.

import numpy as np
# import numpy as np: importa la libreria NumPy con alias 'np'
# - numpy: libreria fondamentale per il calcolo scientifico in Python
# - as np: crea un alias più breve per comodità (invece di scrivere numpy.array, scriviamo np.array)
# - np è la convenzione standard nella comunità Python
# - Utile perché PyTorch può convertire facilmente tra tensor torch e array numpy


**Initializing a Tensor**

Puo essere fatto in vari modi:

Dal dai dati inizializzati

In [2]:
data = [[1, 2], [3, 4]]
# data = [[1, 2], [3, 4]]: crea una lista di liste in Python
# - Questa struttura rappresenta una matrice 2x2:
#   riga 0: [1, 2]
#   riga 1: [3, 4]

x_data = torch.tensor(data)
# x_data = torch.tensor(data): crea un tensor PyTorch a partire dai dati
# - torch.tensor(): è il costruttore della classe tensor di PyTorch
#   * Converte strutture dati Python (liste, tuple) o numpy array in tensor
#   * Crea una nuova copia dei dati (non condivide memoria con l'originale)
#   * Inferisce automaticamente il tipo di dato (dtype) dai valori
# - data: è la lista di liste che abbiamo appena creato
# - Il risultato è un tensor 2D (matrice) con:
#   * shape: (2, 2) - 2 righe e 2 colonne
#   * dtype: torch.int64 (default per interi) perché i valori sono interi
#   * valori: [[1, 2], [3, 4]]

# Questo è diverso da torch.Tensor() (con la T maiuscola) che:
# - torch.Tensor() è un alias del costruttore predefinito
# - torch.tensor() (minuscola) inferisce il dtype, torch.Tensor() usa sempre float32

Da un array Numpy

In [3]:
np_array = np.array(data)
# np_array = np.array(data): converte la lista di liste in un array NumPy
# - np.array(): è la funzione di NumPy che crea array
#   * data: la nostra lista di liste [[1, 2], [3, 4]]
#   * Crea un array NumPy con gli stessi dati
#   * Inferisce automaticamente il tipo di dato (dtype)
# - Il risultato è un array NumPy 2D con:
#   * shape: (2, 2) - 2 righe e 2 colonne
#   * dtype: int64 (tipicamente, dipende dal sistema)
#   * valori: [[1, 2], [3, 4]]
# - Ora np_array è un oggetto NumPy, non più una lista Python nativa

x_np = torch.from_numpy(np_array)
# x_np = torch.from_numpy(np_array): converte l'array NumPy in tensor PyTorch
# - torch.from_numpy(): è una funzione specifica di PyTorch per convertire array NumPy
#   * Accetta solo array NumPy come input (non liste Python)
#   * È molto efficiente perché CON Divide la memoria con l'array NumPy originale
#   * NON crea una copia, ma condivide lo stesso spazio di memoria
# - Il risultato è un tensor con:
#   * Stessa shape (2, 2) dell'array NumPy
#   * Stesso dtype dell'array NumPy (int64)
#   * Stessi valori [[1, 2], [3, 4]]

# Differenza fondamentale rispetto a torch.tensor(np_array):
# - torch.tensor(np_array): crea SEMPRE una COPIA dei dati (più memoria, indipendente)
# - torch.from_numpy(np_array): CONDIVIDE la memoria (più efficiente, ma attenzione!)
#   * Se modifichi np_array dopo, anche x_np cambia (e viceversa)
#   * Questo comportamento è voluto per efficienza quando si lavora con grandi dataset

Da un altro tensore

In [4]:
x_ones = torch.ones_like(x_data)
# x_ones = torch.ones_like(x_data): crea un tensor di uni con la stessa forma di x_data
# - torch.ones_like(): è una funzione che crea un tensor riempito con il valore 1
#   * "like" significa "simile a" - usa un tensor esistente come modello
#   * x_data: è il tensor modello (il nostro tensor [[1, 2], [3, 4]])
#   * Eredita automaticamente tutte le proprietà di x_data:
#     - shape: (2, 2) - stessa dimensione
#     - dtype: torch.int64 (perché x_data era intero)
#     - device: CPU (se x_data era su CPU)
#     - requires_grad: False (se x_data non richiedeva gradienti)
#   * Sovrascrive i valori: tutti diventano 1
# - Il risultato x_ones sarà: tensor([[1, 1], [1, 1]]) con dtype=int64

print(f"Ones Tensor: \n {x_ones} \n")
# print(f"Ones Tensor: \n {x_ones} \n"): stampa il tensor con formattazione
# - f"..." : f-string di Python (formattazione stringhe)
# - \n : newline (vai a capo) per miglior leggibilità. (aggiunge riga finale)
# - {x_ones} : inserisce il valore del tensor nella stringa

x_rand = torch.rand_like(x_data, dtype=torch.float)
# x_rand = torch.rand_like(x_data, dtype=torch.float): crea tensor casuale
# - torch.rand_like(): crea un tensor con valori casuali uniformi tra 0 e 1
#   * Usa x_data come modello per la shape (2, 2)
#   * dtype=torch.float: SOVRASCRIVE il tipo di dato originale
#     - x_data era int64, ma noi vogliamo float per i numeri casuali
#     - torch.float è l'equivalente di float32 in PyTorch
#   * I valori sono casuali da distribuzione uniforme U[0, 1)
# - Il risultato sarà qualcosa come: tensor([[0.1234, 0.5678], [0.9101, 0.1121]])

print(f"Random Tensor: \n {x_rand} \n")
# print(f"Random Tensor: \n {x_rand} \n"): stampa il tensor casuale
# - Stessa formattazione del primo print
# - Mostrerà valori decimali casuali tra 0 e 1

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9827, 0.4902],
        [0.6558, 0.6095]]) 



With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



shape (o forma) è una tupla che descrive le dimensioni del tensor.

- Una tupla in Python è una sequenza immutabile tra parentesi tonde: ( , )

- Ogni numero nella tupla rappresenta la dimensione di un asse (axis)

- Di fatto è una tabella, puo contenere di tutto, un tesnore è una matrice, puo contenere solo numeri

In [5]:
shape = (2,3,)
# shape = (2,3,): definisce una tupla che specifica le dimensioni del tensor
# - (2,3,) è una tupla con due elementi: 2 e 3 (la virgola finale è opzionale in Python)
# - Primo elemento (2): indica 2 righe (prima dimensione)
# - Secondo elemento (3): indica 3 colonne (seconda dimensione)
# - Questa tupla descrive un tensor 2D con shape (2, 3)
# - La virgola dopo il 3 è opzionale, ma a volte si usa per chiarezza o per tuple con un elemento

rand_tensor = torch.rand(shape)
# rand_tensor = torch.rand(shape): crea un tensor con valori casuali uniformi
# - torch.rand(): funzione che genera valori casuali da distribuzione uniforme U[0, 1)
#   * La distribuzione è uniforme: tutti i valori hanno stessa probabilità
# - shape: la tupla (2,3) che abbiamo definito, dice a torch.rand che formato dare al tensor
# - Il risultato è un tensor 2x3 con valori casuali come:
#   tensor([[0.1234, 0.5678, 0.9012],
#           [0.3456, 0.7890, 0.2345]])

ones_tensor = torch.ones(shape)
# ones_tensor = torch.ones(shape): crea un tensor con tutti valori 1
# - Nota: il dtype predefinito per torch.ones() è torch.float32

zeros_tensor = torch.zeros(shape)
# zeros_tensor = torch.zeros(shape): crea un tensor con tutti valori 0
# - Anche qui il dtype predefinito è torch.float32

print(f"Random Tensor: \n {rand_tensor} \n")
# print(f"Random Tensor: \n {rand_tensor} \n"): stampa il tensor casuale
# - \n aggiunge linee vuote per separare visivamente gli output

print(f"Ones Tensor: \n {ones_tensor} \n")
# print(f"Ones Tensor: \n {ones_tensor} \n"): stampa il tensor di uni
# - Mostrerà tutti 1 in formato float: 1. (con punto decimale)

print(f"Zeros Tensor: \n {zeros_tensor}")
# print(f"Zeros Tensor: \n {zeros_tensor}"): stampa il tensor di zeri
# - Mostrerà tutti 0 in formato float: 0.
# - Nota: qui non c'è \n finale, quindi il prossimo output sarà sulla stessa linea

Random Tensor: 
 tensor([[0.5697, 0.6851, 0.3695],
        [0.0602, 0.2176, 0.9518]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Attributes of a Tensor**

Tensor attributes describe their shape, datatype, and the device on which they are stored.

Gli attributi dei tensor descrivono la loro forma, il tipo di dato e il dispositivo su cui sono memorizzati.

In [6]:
tensor = torch.rand(3,4)
# tensor = torch.rand(3,4): crea un tensor 3x4 con valori casuali uniformi tra 0 e 1
# - torch.rand(): funzione che genera valori casuali da distribuzione uniforme U[0, 1)
# - (3,4): specifica la shape del tensor - 3 righe e 4 colonne
# - Il risultato è un tensor 2D (matrice) di dimensioni 3x4
# - I valori saranno diversi ogni volta che eseguiamo il codice
# - dtype predefinito per torch.rand() è torch.float32
# - device predefinito è CPU (se non abbiamo specificato GPU)

print(f"Shape of tensor: {tensor.shape}")
# print(f"Shape of tensor: {tensor.shape}"): stampa la forma/dimensioni del tensor
# - f"..." : f-string (formattazione stringhe) di Python
# - {tensor.shape}: inserisce il valore dell'attributo .shape nella stringa
# - .shape è un attributo del tensor che restituisce un oggetto torch.Size
# - torch.Size è essenzialmente una tupla che contiene le dimensioni
# - Output tipico: "Shape of tensor: torch.Size([3, 4])"
#   * Questo significa: 3 righe, 4 colonne
#   * È un tensor 2D con 12 elementi totali (3×4=12)

print(f"Datatype of tensor: {tensor.dtype}")
# print(f"Datatype of tensor: {tensor.dtype}"): stampa il tipo di dato degli elementi
# - {tensor.dtype}: inserisce il valore dell'attributo .dtype nella stringa
# - .dtype indica che tipo di numeri contiene il tensor
# - Per torch.rand(), il dtype predefinito è torch.float32
# - Output tipico: "Datatype of tensor: torch.float32"
#   * float32 significa: numero decimale a 32 bit (virgola mobile a singola precisione)
#   * È il formato standard per deep learning perché bilancia precisione e memoria

print(f"Device tensor is stored on: {tensor.device}")
# print(f"Device tensor is stored on: {tensor.device}"): stampa dove è memorizzato il tensor
# - {tensor.device}: inserisce il valore dell'attributo .device nella stringa
# - .device indica se il tensor è su CPU o GPU
# - Di default, se non specifichiamo, tutti i tensor sono su CPU
# - Output tipico: "Device tensor is stored on: cpu"
#   * "cpu" significa che il tensor è nella memoria RAM, elaborato dalla CPU
#   * Se fossimo su GPU, vedremmo qualcosa come "cuda:0"

# L'output completo sarà qualcosa come:
# Shape of tensor: torch.Size([3, 4])
# Datatype of tensor: torch.float32
# Device tensor is stored on: cpu

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Operations on Tensors**

Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU. Them runs on the GPU and each Accelerator has a call for each device (Nvidia; Apple ecc..)   If you’re using Colab, allocate an accelerator by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [ ]:
# We move our tensor to the current accelerator if available

# - Questa è una riga di commento che spiega cosa fa il codice sottostante
# - "accelerator" è un termine generico per qualsiasi dispositivo che accelera i calcoli (GPU, MPS, ecc.)

if torch.accelerator.is_available():
# if torch.accelerator.is_available(): verifica se c'è un acceleratore disponibile
# - torch.accelerator: è un modulo di PyTorch per gestire acceleratori in modo uniforme
# - .is_available(): è un metodo che restituisce True/False
#   * True: se c'è almeno un acceleratore (GPU NVIDIA, GPU Apple, ecc.) disponibile
#   * False: se nessun acceleratore è disponibile (solo CPU)

    tensor = tensor.to(torch.accelerator.current_accelerator())
    # tensor = tensor.to(...): sposta il tensor su un dispositivo specifico
    # - .to() è il metodo di PyTorch per spostare tensor tra dispositivi
    #   * Può spostare da CPU a GPU, da GPU a CPU, tra GPU diverse, ecc.
    #   * Crea una copia del tensor nel nuovo dispositivo se necessario

    # torch.accelerator.current_accelerator(): ottiene l'acceleratore corrente
    # - current_accelerator(): metodo che restituisce l'acceleratore attualmente in uso
    #   * Di solito è il primo/dispositivo predefinito disponibile
    #   * Restituisce un oggetto torch.device
    #   * Esempi: device(type='cuda', index=0) o device(type='mps', index=0)

    # In pratica, questa riga dice: "sposta il tensor su qualsiasi acceleratore sia disponibile"

# Il risultato finale:
# - Se c'è una GPU NVIDIA (CUDA): tensor sarà su cuda:0
# - Se c'è un Mac con chip M1/M2 (MPS): tensor sarà su mps:0
# - Se non c'è acceleratore: tensor rimane su CPU (perché l'if è falso)